## Exercise 6 - Numpy

1 Generate two NumPy arrays so that first array has integers from 10 to 40 (inclusive). Second array should have integers from 220 to 250 (inclusive). Sum these arrays and present the result array.

2 Generate two-dimensional array with 10 rows and 7 columns containing integers starting from 100.

3 Generate two one-dimensional arrays having integers between 1-50. First array should have even and second array should have odd numbers. Finally multiply each element from corresponding index positions from these two arrays for the result array. For example [(1 x 2),(3 x 4),(5 x 6),(7 x 8)...].

4 Generate two-dimensional array (40 rows, 5 columns) containing random integers between 1 and 1000. Filter the result array so that only numbers divisable with numbers 2 and 5 are presented (number must be divisable with both).

In [30]:
# E1
import numpy as np

array1 = np.arange(10, 41)
array2 = np.arange(220, 251)

result = array1 + array2

print(result)

[230 232 234 236 238 240 242 244 246 248 250 252 254 256 258 260 262 264
 266 268 270 272 274 276 278 280 282 284 286 288 290]


In [31]:
# E2
import numpy as np

starto = 100
row = 10
column = 7

array_secando_dime = np.arange(starto, starto + row * column).reshape(row, column)

array_secando_dime

array([[100, 101, 102, 103, 104, 105, 106],
       [107, 108, 109, 110, 111, 112, 113],
       [114, 115, 116, 117, 118, 119, 120],
       [121, 122, 123, 124, 125, 126, 127],
       [128, 129, 130, 131, 132, 133, 134],
       [135, 136, 137, 138, 139, 140, 141],
       [142, 143, 144, 145, 146, 147, 148],
       [149, 150, 151, 152, 153, 154, 155],
       [156, 157, 158, 159, 160, 161, 162],
       [163, 164, 165, 166, 167, 168, 169]])

In [32]:
# E3
import numpy as np

starto = 1
endo = 50

array_even = np.arange(starto + 1, endo + 1, 2)
array_odd = np.arange(starto, endo + 1, 2)

result = array_even * array_odd

result

array([   2,   12,   30,   56,   90,  132,  182,  240,  306,  380,  462,
        552,  650,  756,  870,  992, 1122, 1260, 1406, 1560, 1722, 1892,
       2070, 2256, 2450])

In [34]:
# E4
import numpy as np

row = 40
column = 5

array_secando_dime = np.random.randint(1, 1001, size=(row, column))

filtering = (array_secando_dime % 2 == 0) & (array_secando_dime % 5 == 0)

filtered = array_secando_dime[filtering]

filtered

array([680,  40, 830, 650, 240, 170, 790,  20, 750, 700, 210, 820, 920,
       990, 150, 920, 970])